<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            // Europa
            ['code' => 'AD', 'name' => 'Andorra', 'nationality' => 'Andorrà/na', 'continent' => 'Europa'],
            ['code' => 'AL', 'name' => 'Albània', 'nationality' => 'Albanès/a', 'continent' => 'Europa'],
            ['code' => 'AT', 'name' => 'Àustria', 'nationality' => 'Austríac/a', 'continent' => 'Europa'],
            ['code' => 'BA', 'name' => 'Bòsnia i Hercegovina', 'nationality' => 'Bosnià/na', 'continent' => 'Europa'],
            ['code' => 'BE', 'name' => 'Bèlgica', 'nationality' => 'Belga', 'continent' => 'Europa'],
            ['code' => 'BG', 'name' => 'Bulgària', 'nationality' => 'Búlgar/a', 'continent' => 'Europa'],
            ['code' => 'BY', 'name' => 'Bielorússia', 'nationality' => 'Bielorús/sa', 'continent' => 'Europa'],
            ['code' => 'CH', 'name' => 'Suïssa', 'nationality' => 'Suís/sa', 'continent' => 'Europa'],
            ['code' => 'CY', 'name' => 'Xipre', 'nationality' => 'Xipriota', 'continent' => 'Europa'],
            ['code' => 'CZ', 'name' => 'Txèquia', 'nationality' => 'Txec/a', 'continent' => 'Europa'],
            ['code' => 'DE', 'name' => 'Alemanya', 'nationality' => 'Alemany/a', 'continent' => 'Europa'],
            ['code' => 'DK', 'name' => 'Dinamarca', 'nationality' => 'Danès/a', 'continent' => 'Europa'],
            ['code' => 'EE', 'name' => 'Estònia', 'nationality' => 'Estonià/na', 'continent' => 'Europa'],
            ['code' => 'ES', 'name' => 'Espanya', 'nationality' => 'Espanyol/a', 'continent' => 'Europa'],
            ['code' => 'FI', 'name' => 'Finlàndia', 'nationality' => 'Finlandès/a', 'continent' => 'Europa'],
            ['code' => 'FR', 'name' => 'França', 'nationality' => 'Francès/a', 'continent' => 'Europa'],
            ['code' => 'GB', 'name' => 'Regne Unit', 'nationality' => 'Britànic/a', 'continent' => 'Europa'],
            ['code' => 'GR', 'name' => 'Grècia', 'nationality' => 'Grec/a', 'continent' => 'Europa'],
            ['code' => 'HR', 'name' => 'Croàcia', 'nationality' => 'Croat/a', 'continent' => 'Europa'],
            ['code' => 'HU', 'name' => 'Hongria', 'nationality' => 'Hongarès/a', 'continent' => 'Europa'],
            ['code' => 'IE', 'name' => 'Irlanda', 'nationality' => 'Irlandès/a', 'continent' => 'Europa'],
            ['code' => 'IS', 'name' => 'Islàndia', 'nationality' => 'Islandès/a', 'continent' => 'Europa'],
            ['code' => 'IT', 'name' => 'Itàlia', 'nationality' => 'Italià/na', 'continent' => 'Europa'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'nationality' => 'Liechtensteinès/a', 'continent' => 'Europa'],
            ['code' => 'LT', 'name' => 'Lituània', 'nationality' => 'Lituà/na', 'continent' => 'Europa'],
            ['code' => 'LU', 'name' => 'Luxemburg', 'nationality' => 'Luxemburguès/a', 'continent' => 'Europa'],
            ['code' => 'LV', 'name' => 'Letònia', 'nationality' => 'Letó/na', 'continent' => 'Europa'],
            ['code' => 'MC', 'name' => 'Mònaco', 'nationality' => 'Monegasc/a', 'continent' => 'Europa'],
            ['code' => 'MD', 'name' => 'Moldàvia', 'nationality' => 'Moldau/ava', 'continent' => 'Europa'],
            ['code' => 'ME', 'name' => 'Montenegro', 'nationality' => 'Montenegrí/na', 'continent' => 'Europa'],
            ['code' => 'MK', 'name' => 'Macedònia del Nord', 'nationality' => 'Macedoni/a', 'continent' => 'Europa'],
            ['code' => 'MT', 'name' => 'Malta', 'nationality' => 'Maltès/a', 'continent' => 'Europa'],
            ['code' => 'NL', 'name' => 'Països Baixos', 'nationality' => 'Neerlandès/a', 'continent' => 'Europa'],
            ['code' => 'NO', 'name' => 'Noruega', 'nationality' => 'Noruec/ga', 'continent' => 'Europa'],
            ['code' => 'PL', 'name' => 'Polònia', 'nationality' => 'Polonès/a', 'continent' => 'Europa'],
            ['code' => 'PT', 'name' => 'Portugal', 'nationality' => 'Portuguès/a', 'continent' => 'Europa'],
            ['code' => 'RO', 'name' => 'Romania', 'nationality' => 'Romanès/a', 'continent' => 'Europa'],
            ['code' => 'RS', 'name' => 'Sèrbia', 'nationality' => 'Serbi/a', 'continent' => 'Europa'],
            ['code' => 'RU', 'name' => 'Rússia', 'nationality' => 'Rus/sa', 'continent' => 'Europa'],
            ['code' => 'SE', 'name' => 'Suècia', 'nationality' => 'Suec/a', 'continent' => 'Europa'],
            ['code' => 'SI', 'name' => 'Eslovènia', 'nationality' => 'Eslovè/na', 'continent' => 'Europa'],
            ['code' => 'SK', 'name' => 'Eslovàquia', 'nationality' => 'Eslovac/a', 'continent' => 'Europa'],
            ['code' => 'SM', 'name' => 'San Marino', 'nationality' => 'Sanmarinès/a', 'continent' => 'Europa'],
            ['code' => 'UA', 'name' => 'Ucraïna', 'nationality' => 'Ucraïnès/a', 'continent' => 'Europa'],
            ['code' => 'VA', 'name' => 'Ciutat del Vaticà', 'nationality' => 'Vaticà/na', 'continent' => 'Europa'],
            ['code' => 'XK', 'name' => 'Kosovo', 'nationality' => 'Kosovar/a', 'continent' => 'Europa'],

            // Àsia
            ['code' => 'AE', 'name' => 'Emirats Àrabs Units', 'nationality' => 'Emiratí', 'continent' => 'Àsia'],
            ['code' => 'AF', 'name' => 'Afganistan', 'nationality' => 'Afganès/a', 'continent' => 'Àsia'],
            ['code' => 'AM', 'name' => 'Armènia', 'nationality' => 'Armeni/a', 'continent' => 'Àsia'],
            ['code' => 'AZ', 'name' => 'Azerbaidjan', 'nationality' => 'Azerbaidjanès/a', 'continent' => 'Àsia'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'nationality' => 'Bengalí', 'continent' => 'Àsia'],
            ['code' => 'BH', 'name' => 'Bahrain', 'nationality' => 'Bahrainí', 'continent' => 'Àsia'],
            ['code' => 'BN', 'name' => 'Brunei', 'nationality' => 'Bruneià/na', 'continent' => 'Àsia'],
            ['code' => 'BT', 'name' => 'Bhutan', 'nationality' => 'Butanès/a', 'continent' => 'Àsia'],
            ['code' => 'CN', 'name' => 'Xina', 'nationality' => 'Xinès/a', 'continent' => 'Àsia'],
            ['code' => 'GE', 'name' => 'Geòrgia', 'nationality' => 'Georgià/na', 'continent' => 'Àsia'],
            ['code' => 'HK', 'name' => 'Hong Kong', 'nationality' => 'Hongkonguès/a', 'continent' => 'Àsia'],
            ['code' => 'ID', 'name' => 'Indonèsia', 'nationality' => 'Indonesi/a', 'continent' => 'Àsia'],
            ['code' => 'IL', 'name' => 'Israel', 'nationality' => 'Israelià/na', 'continent' => 'Àsia'],
            ['code' => 'IN', 'name' => 'Índia', 'nationality' => 'Indi/a', 'continent' => 'Àsia'],
            ['code' => 'IQ', 'name' => 'Iraq', 'nationality' => 'Iraquià/na', 'continent' => 'Àsia'],
            ['code' => 'IR', 'name' => 'Iran', 'nationality' => 'Iranià/na', 'continent' => 'Àsia'],
            ['code' => 'JO', 'name' => 'Jordània', 'nationality' => 'Jordà/na', 'continent' => 'Àsia'],
            ['code' => 'JP', 'name' => 'Japó', 'nationality' => 'Japonès/a', 'continent' => 'Àsia'],
            ['code' => 'KG', 'name' => 'Kirguizistan', 'nationality' => 'Kirguís', 'continent' => 'Àsia'],
            ['code' => 'KH', 'name' => 'Cambodja', 'nationality' => 'Cambodjà/na', 'continent' => 'Àsia'],
            ['code' => 'KP', 'name' => 'Corea del Nord', 'nationality' => 'Nord-coreà/na', 'continent' => 'Àsia'],
            ['code' => 'KR', 'name' => 'Corea del Sud', 'nationality' => 'Sud-coreà/na', 'continent' => 'Àsia'],
            ['code' => 'KW', 'name' => 'Kuwait', 'nationality' => 'Kuwaitià/na', 'continent' => 'Àsia'],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'nationality' => 'Kazakh', 'continent' => 'Àsia'],
            ['code' => 'LA', 'name' => 'Laos', 'nationality' => 'Laosià/na', 'continent' => 'Àsia'],
            ['code' => 'LB', 'name' => 'Líban', 'nationality' => 'Libanès/a', 'continent' => 'Àsia'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'nationality' => 'Cingalès/a', 'continent' => 'Àsia'],
            ['code' => 'MM', 'name' => 'Myanmar', 'nationality' => 'Birmà/na', 'continent' => 'Àsia'],
            ['code' => 'MN', 'name' => 'Mongòlia', 'nationality' => 'Mongol/a', 'continent' => 'Àsia'],
            ['code' => 'MO', 'name' => 'Macau', 'nationality' => 'Macaués/esa', 'continent' => 'Àsia'],
            ['code' => 'MV', 'name' => 'Maldives', 'nationality' => 'Maldiu/iva', 'continent' => 'Àsia'],
            ['code' => 'MY', 'name' => 'Malàisia', 'nationality' => 'Malaisi/a', 'continent' => 'Àsia'],
            ['code' => 'NP', 'name' => 'Nepal', 'nationality' => 'Nepalès/a', 'continent' => 'Àsia'],
            ['code' => 'OM', 'name' => 'Oman', 'nationality' => 'Omanita', 'continent' => 'Àsia'],
            ['code' => 'PH', 'name' => 'Filipines', 'nationality' => 'Filipí/na', 'continent' => 'Àsia'],
            ['code' => 'PK', 'name' => 'Pakistan', 'nationality' => 'Pakistanès/a', 'continent' => 'Àsia'],
            ['code' => 'PS', 'name' => 'Palestina', 'nationality' => 'Palestí/na', 'continent' => 'Àsia'],
            ['code' => 'QA', 'name' => 'Qatar', 'nationality' => 'Qatarià/na', 'continent' => 'Àsia'],
            ['code' => 'SA', 'name' => 'Aràbia Saudita', 'nationality' => 'Saudita', 'continent' => 'Àsia'],
            ['code' => 'SG', 'name' => 'Singapur', 'nationality' => 'Singapurès/a', 'continent' => 'Àsia'],
            ['code' => 'SY', 'name' => 'Síria', 'nationality' => 'Sirià/na', 'continent' => 'Àsia'],
            ['code' => 'TH', 'name' => 'Tailàndia', 'nationality' => 'Tailandès/a', 'continent' => 'Àsia'],
            ['code' => 'TJ', 'name' => 'Tadjikistan', 'nationality' => 'Tadjik', 'continent' => 'Àsia'],
            ['code' => 'TL', 'name' => 'Timor Oriental', 'nationality' => 'Timorès/a', 'continent' => 'Àsia'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'nationality' => 'Turcman/ana', 'continent' => 'Àsia'],
            ['code' => 'TR', 'name' => 'Turquia', 'nationality' => 'Turc/a', 'continent' => 'Àsia'],
            ['code' => 'TW', 'name' => 'Taiwan', 'nationality' => 'Taiwanès/a', 'continent' => 'Àsia'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'nationality' => 'Uzbek', 'continent' => 'Àsia'],
            ['code' => 'VN', 'name' => 'Vietnam', 'nationality' => 'Vietnamita', 'continent' => 'Àsia'],
            ['code' => 'YE', 'name' => 'Iemen', 'nationality' => 'Iemenita', 'continent' => 'Àsia'],

            // Àfrica
            ['code' => 'AO', 'name' => 'Angola', 'nationality' => 'Angolès/a', 'continent' => 'Àfrica'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'nationality' => 'Burkinès/a', 'continent' => 'Àfrica'],
            ['code' => 'BI', 'name' => 'Burundi', 'nationality' => 'Burundès/a', 'continent' => 'Àfrica'],
            ['code' => 'BJ', 'name' => 'Benín', 'nationality' => 'Beninès/a', 'continent' => 'Àfrica'],
            ['code' => 'BW', 'name' => 'Botswana', 'nationality' => 'Botswanès/a', 'continent' => 'Àfrica'],
            ['code' => 'CD', 'name' => 'Rep. Democràtica del Congo', 'nationality' => 'Congolès/a', 'continent' => 'Àfrica'],
            ['code' => 'CF', 'name' => 'República Centreafricana', 'nationality' => 'Centreafricà/na', 'continent' => 'Àfrica'],
            ['code' => 'CG', 'name' => 'Congo', 'nationality' => 'Congolès/a', 'continent' => 'Àfrica'],
            ['code' => 'CI', 'name' => "Costa d'Ivori", 'nationality' => 'Ivorià/na', 'continent' => 'Àfrica'],
            ['code' => 'CM', 'name' => 'Camerun', 'nationality' => 'Camerunès/a', 'continent' => 'Àfrica'],
            ['code' => 'CV', 'name' => 'Cap Verd', 'nationality' => 'Capverdià/na', 'continent' => 'Àfrica'],
            ['code' => 'DJ', 'name' => 'Djibouti', 'nationality' => 'Djiboutià/na', 'continent' => 'Àfrica'],
            ['code' => 'DZ', 'name' => 'Algèria', 'nationality' => 'Algerià/na', 'continent' => 'Àfrica'],
            ['code' => 'EG', 'name' => 'Egipte', 'nationality' => 'Egipci/a', 'continent' => 'Àfrica'],
            ['code' => 'EH', 'name' => 'Sàhara Occidental', 'nationality' => 'Sahrauí', 'continent' => 'Àfrica'],
            ['code' => 'ER', 'name' => 'Eritrea', 'nationality' => 'Eritreu/a', 'continent' => 'Àfrica'],
            ['code' => 'ET', 'name' => 'Etiòpia', 'nationality' => 'Etíop', 'continent' => 'Àfrica'],
            ['code' => 'GA', 'name' => 'Gabon', 'nationality' => 'Gabonès/a', 'continent' => 'Àfrica'],
            ['code' => 'GH', 'name' => 'Ghana', 'nationality' => 'Ghanès/a', 'continent' => 'Àfrica'],
            ['code' => 'GM', 'name' => 'Gàmbia', 'nationality' => 'Gambià/na', 'continent' => 'Àfrica'],
            ['code' => 'GN', 'name' => 'Guinea', 'nationality' => 'Guineà/na', 'continent' => 'Àfrica'],
            ['code' => 'GQ', 'name' => 'Guinea Equatorial', 'nationality' => 'Equatoguineà/na', 'continent' => 'Àfrica'],
            ['code' => 'GW', 'name' => 'Guinea Bissau', 'nationality' => 'Guineà/na', 'continent' => 'Àfrica'],
            ['code' => 'KE', 'name' => 'Kenya', 'nationality' => 'Kenyà/na', 'continent' => 'Àfrica'],
            ['code' => 'KM', 'name' => 'Comores', 'nationality' => 'Comorià/na', 'continent' => 'Àfrica'],
            ['code' => 'LR', 'name' => 'Libèria', 'nationality' => 'Liberià/na', 'continent' => 'Àfrica'],
            ['code' => 'LS', 'name' => 'Lesotho', 'nationality' => 'Lesothenc/a', 'continent' => 'Àfrica'],
            ['code' => 'LY', 'name' => 'Líbia', 'nationality' => 'Libi/a', 'continent' => 'Àfrica'],
            ['code' => 'MA', 'name' => 'Marroc', 'nationality' => 'Marroquí', 'continent' => 'Àfrica'],
            ['code' => 'MG', 'name' => 'Madagascar', 'nationality' => 'Malgaix/a', 'continent' => 'Àfrica'],
            ['code' => 'ML', 'name' => 'Mali', 'nationality' => 'Malià/na', 'continent' => 'Àfrica'],
            ['code' => 'MR', 'name' => 'Mauritània', 'nationality' => 'Maurità/na', 'continent' => 'Àfrica'],
            ['code' => 'MU', 'name' => 'Maurici', 'nationality' => 'Maurici/ana', 'continent' => 'Àfrica'],
            ['code' => 'MW', 'name' => 'Malawi', 'nationality' => 'Malawià/na', 'continent' => 'Àfrica'],
            ['code' => 'MZ', 'name' => 'Moçambic', 'nationality' => 'Moçambiquès/a', 'continent' => 'Àfrica'],
            ['code' => 'NA', 'name' => 'Namíbia', 'nationality' => 'Namibià/na', 'continent' => 'Àfrica'],
            ['code' => 'NE', 'name' => 'Níger', 'nationality' => 'Nigerí/na', 'continent' => 'Àfrica'],
            ['code' => 'NG', 'name' => 'Nigèria', 'nationality' => 'Nigerià/na', 'continent' => 'Àfrica'],
            ['code' => 'RW', 'name' => 'Rwanda', 'nationality' => 'Rwandès/a', 'continent' => 'Àfrica'],
            ['code' => 'SC', 'name' => 'Seychelles', 'nationality' => 'Seychellès/a', 'continent' => 'Àfrica'],
            ['code' => 'SD', 'name' => 'Sudan', 'nationality' => 'Sudanès/a', 'continent' => 'Àfrica'],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'nationality' => 'Sierraleonès/a', 'continent' => 'Àfrica'],
            ['code' => 'SN', 'name' => 'Senegal', 'nationality' => 'Senegalès/a', 'continent' => 'Àfrica'],
            ['code' => 'SO', 'name' => 'Somàlia', 'nationality' => 'Somali', 'continent' => 'Àfrica'],
            ['code' => 'SS', 'name' => 'Sudan del Sud', 'nationality' => 'Sud-sudanès/a', 'continent' => 'Àfrica'],
            ['code' => 'ST', 'name' => 'São Tomé i Príncipe', 'nationality' => 'Santomès/a', 'continent' => 'Àfrica'],
            ['code' => 'SZ', 'name' => 'Eswatini', 'nationality' => 'Swazi', 'continent' => 'Àfrica'],
            ['code' => 'TD', 'name' => 'Txad', 'nationality' => 'Txadià/na', 'continent' => 'Àfrica'],
            ['code' => 'TG', 'name' => 'Togo', 'nationality' => 'Togolès/a', 'continent' => 'Àfrica'],
            ['code' => 'TN', 'name' => 'Tunísia', 'nationality' => 'Tunisià/na', 'continent' => 'Àfrica'],
            ['code' => 'TZ', 'name' => 'Tanzània', 'nationality' => 'Tanzà/na', 'continent' => 'Àfrica'],
            ['code' => 'UG', 'name' => 'Uganda', 'nationality' => 'Ugandès/a', 'continent' => 'Àfrica'],
            ['code' => 'ZA', 'name' => 'Sud-àfrica', 'nationality' => 'Sud-africà/na', 'continent' => 'Àfrica'],
            ['code' => 'ZM', 'name' => 'Zàmbia', 'nationality' => 'Zambià/na', 'continent' => 'Àfrica'],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'nationality' => 'Zimbabuès/a', 'continent' => 'Àfrica'],

            // Amèrica del Nord
            ['code' => 'AG', 'name' => 'Antigua i Barbuda', 'nationality' => 'Antiguà/na', 'continent' => 'Amèrica'],
            ['code' => 'BB', 'name' => 'Barbados', 'nationality' => 'Barbadià/na', 'continent' => 'Amèrica'],
            ['code' => 'BS', 'name' => 'Bahames', 'nationality' => 'Bahamià/na', 'continent' => 'Amèrica'],
            ['code' => 'BZ', 'name' => 'Belize', 'nationality' => 'Beliceny/a', 'continent' => 'Amèrica'],
            ['code' => 'CA', 'name' => 'Canadà', 'nationality' => 'Canadenc/a', 'continent' => 'Amèrica'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'nationality' => 'Costa-riqueny/a', 'continent' => 'Amèrica'],
            ['code' => 'CU', 'name' => 'Cuba', 'nationality' => 'Cubà/na', 'continent' => 'Amèrica'],
            ['code' => 'DM', 'name' => 'Dominica', 'nationality' => 'Dominiqueny/a', 'continent' => 'Amèrica'],
            ['code' => 'DO', 'name' => 'República Dominicana', 'nationality' => 'Dominicà/na', 'continent' => 'Amèrica'],
            ['code' => 'GD', 'name' => 'Grenada', 'nationality' => 'Grenadí/na', 'continent' => 'Amèrica'],
            ['code' => 'GT', 'name' => 'Guatemala', 'nationality' => 'Guatemalenc/a', 'continent' => 'Amèrica'],
            ['code' => 'HN', 'name' => 'Hondures', 'nationality' => 'Hondureny/a', 'continent' => 'Amèrica'],
            ['code' => 'HT', 'name' => 'Haití', 'nationality' => 'Haitià/na', 'continent' => 'Amèrica'],
            ['code' => 'JM', 'name' => 'Jamaica', 'nationality' => 'Jamaicà/na', 'continent' => 'Amèrica'],
            ['code' => 'KN', 'name' => 'Saint Kitts i Nevis', 'nationality' => 'Sant-cristobaleny/a', 'continent' => 'Amèrica'],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'nationality' => 'Santalucià/na', 'continent' => 'Amèrica'],
            ['code' => 'MX', 'name' => 'Mèxic', 'nationality' => 'Mexicà/na', 'continent' => 'Amèrica'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'nationality' => 'Nicaragüeny/a', 'continent' => 'Amèrica'],
            ['code' => 'PA', 'name' => 'Panamà', 'nationality' => 'Panameny/a', 'continent' => 'Amèrica'],
            ['code' => 'SV', 'name' => 'El Salvador', 'nationality' => 'Salvadoreny/a', 'continent' => 'Amèrica'],
            ['code' => 'TT', 'name' => 'Trinitat i Tobago', 'nationality' => 'Trinitari/ària', 'continent' => 'Amèrica'],
            ['code' => 'US', 'name' => 'Estats Units', 'nationality' => 'Estatunidenc/a', 'continent' => 'Amèrica'],
            ['code' => 'VC', 'name' => 'Sant Vicenç i Granadines', 'nationality' => 'Sant-vicentí/na', 'continent' => 'Amèrica'],

            // Amèrica del Sud
            ['code' => 'AR', 'name' => 'Argentina', 'nationality' => 'Argentí/na', 'continent' => 'Amèrica'],
            ['code' => 'BO', 'name' => 'Bolívia', 'nationality' => 'Bolivià/na', 'continent' => 'Amèrica'],
            ['code' => 'BR', 'name' => 'Brasil', 'nationality' => 'Brasiler/a', 'continent' => 'Amèrica'],
            ['code' => 'CL', 'name' => 'Xile', 'nationality' => 'Xilè/na', 'continent' => 'Amèrica'],
            ['code' => 'CO', 'name' => 'Colòmbia', 'nationality' => 'Colombià/na', 'continent' => 'Amèrica'],
            ['code' => 'EC', 'name' => 'Equador', 'nationality' => 'Equatorià/na', 'continent' => 'Amèrica'],
            ['code' => 'GY', 'name' => 'Guyana', 'nationality' => 'Guyanès/a', 'continent' => 'Amèrica'],
            ['code' => 'PE', 'name' => 'Perú', 'nationality' => 'Peruà/na', 'continent' => 'Amèrica'],
            ['code' => 'PY', 'name' => 'Paraguai', 'nationality' => 'Paraguaià/na', 'continent' => 'Amèrica'],
            ['code' => 'SR', 'name' => 'Surinam', 'nationality' => 'Surinamès/a', 'continent' => 'Amèrica'],
            ['code' => 'UY', 'name' => 'Uruguai', 'nationality' => 'Uruguaià/na', 'continent' => 'Amèrica'],
            ['code' => 'VE', 'name' => 'Veneçuela', 'nationality' => 'Veneçolà/na', 'continent' => 'Amèrica'],

            // Oceania
            ['code' => 'AU', 'name' => 'Austràlia', 'nationality' => 'Australià/na', 'continent' => 'Oceania'],
            ['code' => 'FJ', 'name' => 'Fiji', 'nationality' => 'Fijià/na', 'continent' => 'Oceania'],
            ['code' => 'FM', 'name' => 'Micronèsia', 'nationality' => 'Micronesi/a', 'continent' => 'Oceania'],
            ['code' => 'KI', 'name' => 'Kiribati', 'nationality' => 'Kiribatià/na', 'continent' => 'Oceania'],
            ['code' => 'MH', 'name' => 'Illes Marshall', 'nationality' => 'Marshallès/a', 'continent' => 'Oceania'],
            ['code' => 'NR', 'name' => 'Nauru', 'nationality' => 'Nauruà/na', 'continent' => 'Oceania'],
            ['code' => 'NZ', 'name' => 'Nova Zelanda', 'nationality' => 'Neozelandès/a', 'continent' => 'Oceania'],
            ['code' => 'PG', 'name' => 'Papua Nova Guinea', 'nationality' => 'Papú', 'continent' => 'Oceania'],
            ['code' => 'PW', 'name' => 'Palau', 'nationality' => 'Palauà/na', 'continent' => 'Oceania'],
            ['code' => 'SB', 'name' => 'Illes Salomó', 'nationality' => 'Salomonenc/a', 'continent' => 'Oceania'],
            ['code' => 'TO', 'name' => 'Tonga', 'nationality' => 'Tonguès/a', 'continent' => 'Oceania'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'nationality' => 'Tuvaluà/na', 'continent' => 'Oceania'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'nationality' => 'Vanuatuà/na', 'continent' => 'Oceania'],
            ['code' => 'WS', 'name' => 'Samoa', 'nationality' => 'Samoà/na', 'continent' => 'Oceania'],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(['code' => $country['code']], $country);
        }
    }
}
